name: flutter_sticky_header
description: Flutter implementation of sticky headers as a sliver. Use it in a CustomScrollView.
version: 0.3.4-web
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/flutter_sticky_header

dependencies:
  #flutter:
  #  sdk: flutter
  flutter_web: any

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  flutter_web_test: any
  test: ^1.6.3

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test